name: GitHub Issues
api:  http://localhost:8081/github/example1
outputs:
  - name: Number of GitHub Issues
    from: number
max value: 100
thresholds:
  - name: Poor
    limit: 30
  - name: Ok
    limit: 50
